kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: pucminas
  name: exp-latency-1
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - pucminas
    labelSelectors:
      app: httpbin
  delay:
    latency: "1000ms"
  duration: "300s"
